Update CHS translation to 0.5.1
vectorwing/FarmersDelight pull request #344
Opened 2021-11-06 15:06 UTC by WuzgXY-GitHub

2021-11-16 02:51 UTC, vectorwing commented
Thanks for the update!

As for the changes you suggested for the en_us lang - "other" was intentional in this case. The Skillet can be operated from either hand: your ingredient can be on your main-hand, so long as you're not currently able to consume it.

Could you please revert that change?

2021-11-16 02:53 UTC, vectorwing requested changes

2021-11-16 02:53 UTC, vectorwing commented on src/main/resources/assets/farmersdelight/lang/en_us.json
> -  "farmersdelight.item.skillet.how_to_cook": "Use your other hand to hold ingredients!",
The use of "other" was intended in this case, as the Skillet can be operated from either hand. Can you please revert the change?

2021-11-16 06:39 UTC, WuzgXY-GitHub commented
Oh yeah, I tested it in creative mode, and foods are always edible in this mode. This is completely due to my carelessness, sorry for that.
I'm currently far away from my PC, and I forgot the password (which is stored in my PC browser) to log into my GitHub account, could you please edit the file by yourself? I think it is maintainer-editable. Sorry again, for inconvenience I brought.

2021-11-26 18:32 UTC, vectorwing commented
Sorry for the really long delay! I got wrapped up into a break and forgot to reply to you. :(

I was going to say it could be done on my end, but thanks for taking the time to revert it. I'll go ahead with the merge. Thanks for the update once again! 👍

2021-11-26 18:33 UTC, vectorwing approved these changes

2021-11-26 18:35 UTC, merged