Update fi_fi.json
vectorwing/FarmersDelight pull request #374
Opened 2022-01-06 14:49 UTC by Markus1002

2022-01-08 23:50 UTC, vectorwing requested changes
Thank you for the update! =)

I noticed a small error with a duplicate ID; could you please fix it before the merge?

2022-01-08 23:50 UTC, vectorwing commented on src/main/resources/assets/farmersdelight/lang/fi_fi.json
> +  "block.farmersdelight.honey_glazed_ham_block": "Lammaspaimenen piiras",
This line seems to have the wrong ID (duplicated from `honey_glazed_ham`, seems to be `shepherds_pie`).
It might error when loading the lang.

2022-01-16 18:34 UTC, Markus1002 commented
Thanks a lot, I fixed it.

2022-01-17 00:45 UTC, vectorwing approved these changes
Thank you!

2022-01-17 00:46 UTC, merged