Candle Cake Fix
vectorwing/FarmersDelight pull request #428
Opened 2022-02-28 01:16 UTC by Umpaz

fixes how FD interacts with modded candle cakes, specifically the cutSlice event

2022-03-05 15:11 UTC, bageldotjpg commented
Personally I'd recommend naming the tag something like `farmersdelight:drops_cake_slice`. This is a bit specific to me since I add Vanilla Cakes, so `vanilla_candle_cakes` is a slightly confusing name overlap since it could mean cakes from Vanilla or made out of Vanilla.

2022-04-03 23:42 UTC, vectorwing requested changes
Sorry for the long delay; finally got time to try this one out.

Yeah, I agree that `drops_cake_slice` is a nicer name, as it becomes a template for other cake slices too. Everything here works fine, just found a small error that needs fixing. 👍

2022-04-03 23:42 UTC, vectorwing commented on src/main/java/vectorwing/farmersdelight/common/item/KnifeItem.java
> +			if (BlockTags.DROPS_CAKE_SLICE.contains(block)) {
This line is pointing to the vanilla tags class, which doesn't contain your new mod tag.
You gotta change it to `ModTags.DROPS_CAKE_SLICE`.

2022-04-03 23:50 UTC, vectorwing approved these changes

2022-04-03 23:51 UTC, merged