CHS Translation
vectorwing/FarmersDelight pull request #49
Opened 2020-08-09 01:09 UTC by WuzgXY-GitHub

@TUsama I wonder if you can help me review this ..(:з」∠)..

2020-08-09 03:22 UTC, TUsama requested changes

2020-08-09 03:22 UTC, TUsama commented on src/main/resources/assets/farmersdelight/lang/zh_cn.json
> +  "item.farmersdelight.stuffed_potato": "填馅马铃薯",
|Feedback Priority|
|---|
|⏳ Sand / Non-blocking but requires future consideration|

酿

2020-08-09 03:22 UTC, TUsama commented on src/main/resources/assets/farmersdelight/lang/zh_cn.json
> +  "farmersdelight.advancement.master_chef.desc": "吃一顿包含每一道可用的菜的大餐！",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

> Eat a course of every meal available!

将全部的菜肴品尝一遍！

available一般不这么翻译，要不翻译成“可以...的”，要不就直接不翻译。
这里存疑，可以问一下Ex

2020-08-09 03:38 UTC, WuzgXY-GitHub commented on src/main/resources/assets/farmersdelight/lang/zh_cn.json
> +  "farmersdelight.advancement.master_chef.desc": "吃一顿包含每一道可用的菜的大餐！",
好的。
@Determancer

2020-08-09 03:38 UTC, WuzgXY-GitHub commented on src/main/resources/assets/farmersdelight/lang/zh_cn.json
> +  "farmersdelight.advancement.master_chef.desc": "吃一顿包含每一道可用的菜的大餐！",
我个人的意见是，可用指的是没被删除的菜，但我也不确定，你的想法很明显比我好。我翻译跌势后也是感到困惑的。

2020-08-09 03:39 UTC, WuzgXY-GitHub commented on src/main/resources/assets/farmersdelight/lang/zh_cn.json
> +  "item.farmersdelight.stuffed_potato": "填馅马铃薯",
Resolve

2020-08-09 03:39 UTC, WuzgXY-GitHub commented on src/main/resources/assets/farmersdelight/lang/zh_cn.json
> +  "item.farmersdelight.stuffed_potato": "填馅马铃薯",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

Resolve

2020-08-09 03:39 UTC, WuzgXY-GitHub commented on src/main/resources/assets/farmersdelight/lang/zh_cn.json
> +  "item.farmersdelight.stuffed_potato": "填馅马铃薯",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

Resolve

2020-08-09 03:41 UTC, WuzgXY-GitHub commented on src/main/resources/assets/farmersdelight/lang/zh_cn.json
> +  "farmersdelight.advancement.master_chef.desc": "吃一顿包含每一道可用的菜的大餐！",
此外，别光看我改了的东西，麻烦也看看其它的部分如何，也是我之前翻译的。

2020-08-09 14:13 UTC, TUsama approved these changes

2020-08-10 21:00 UTC, vectorwing approved these changes
Really cool to see your reviewing process! All I'm able to do is pass some lines through Google Translate, but from what I saw, the updated lines do fit better.

I'll merge it now, if that's okay with you! 😄

2020-08-11 00:07 UTC, WuzgXY-GitHub commented
Yes you can merge it now :)

2020-08-11 05:48 UTC, merged